use_frameworks!

platform :ios, '8.0'

target 'Pod_test_Example' do
  pod 'Pod_test', :path => '../'

  target 'Pod_test_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
